version: '3.8'

services:
  postgres:
    container_name: pgoffice
    image: postgres:10.5
    restart: always
    environment:
      POSTGRES_DB: pgoffice
      POSTGRES_USER: pgofficeadmin
      POSTGRES_PASSWORD: pgofficepassword
    ports:
      - '5555:5432'
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@hotmail.com
      - PGADMIN_DEFAULT_PASSWORD=password

volumes:
  pg_data:
    driver: local